apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: enterprise-order-platform/order-service
    newName: ghcr.io/kazuyabr/demonstracao-habilidade-squadra/order-service
    newTag: main
  - name: enterprise-order-platform/payment-service
    newName: ghcr.io/kazuyabr/demonstracao-habilidade-squadra/payment-service
    newTag: main
  - name: enterprise-order-platform/inventory-service
    newName: ghcr.io/kazuyabr/demonstracao-habilidade-squadra/inventory-service
    newTag: main
  - name: enterprise-order-platform/api-gateway
    newName: ghcr.io/kazuyabr/demonstracao-habilidade-squadra/api-gateway
    newTag: main

patches:
  - target:
      kind: Deployment
      name: order-service
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Deployment
      name: payment-service
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Deployment
      name: inventory-service
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Deployment
      name: api-gateway
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3
