spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:sqlserver://sqlserver:1433;databaseName=saga_db;encrypt=true;trustServerCertificate=true
    username: sa
    password: ${SAGA_DB_PASSWORD}

saga:
  services:
    order-service: http://order-service:8081
    payment-service: http://payment-service:8082
    inventory-service: http://inventory-service:8083

pulsar:
  service-url: pulsar://pulsar:6650
