spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:sqlserver://sqlserver:1433;databaseName=order_db;encrypt=true;trustServerCertificate=true
    username: sa
    password: ${ORDER_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
