server:
  port: 8083

spring:
  application:
    name: inventory-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/inventory_db
      auto-index-creation: true

  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.enterprise.inventory: DEBUG
    org.springframework.web: INFO
