apiVersion: v1
kind: Namespace
metadata:
  name: enterprise-order-platform
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  SPRING_PROFILES_ACTIVE: "docker"
  PULSAR_SERVICE_URL: "pulsar://pulsar:6650"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  SA_PASSWORD: WW91clN0cm9uZyFQYXNzd29yZDEyMw==
  MONGODB_PASSWORD: YWRtaW4xMjM=
